### ISSUE TITLE
WeMO Link Error Message

### ISSUE THREAD

**Issue by jhar3481** [rudders/homebridge-platform-wemo#10]
Hello and thank you so much for this incredible work. I have been semi-successful getting the platform to recognize the Insight Switches I have but when it gets to the WEMO Link - it throws an error no matter how many bulbs i have connected. (I have 8).

I have reset all of the bulbs as well as the Link and reconnected and renamed everything but the error persists. I was wondering if anyone could point me in the right direction?

All bulbs are running the latest firmware (83) and the Wemo Link's firmware is WeMo_WW_2.00.10062.PVT-OWRT-Link

Here's where i'm at:

TV:.homebridge TV$ homebridge
Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
//---
Loaded plugin: homebridge-platform-wemo
Registering platform 'homebridge-platform-wemo.BelkinWeMo'
//---
Loaded config.json with 0 accessories and 2 platforms.
//---
Loading 2 platforms...
Initializing Nest platform...
Fetching Nest devices.
[WeMo Platform] Initializing BelkinWeMo platform...
[WeMo Platform] Wemo Platform Plugin Loaded 
[WeMo Platform] Fetching the Wemo Accessories, expecting 10 and will wait 20 seconds to find them.
[WeMo Platform] Found: Landscaping, type: insight
[WeMo Platform] Landscaping is false
[WeMo Platform] Discovered 1 accessories of 10 
[WeMo Platform] Found: Washer, type: insight
[WeMo Platform] Washer is false
[WeMo Platform] Discovered 2 accessories of 10 
[WeMo Platform] Landscaping binaryState: 1
[WeMo Platform] Washer binaryState: 8
[WeMo Platform] Landscaping binaryState: 1
[WeMo Platform] Washer binaryState: 8
[WeMo Platform] Found: WeMo Link, type: bridge
[WeMo Platform] Found endDevice: Living Room 2, id: 94103EF6BF4312F5
events.js:141
throw er; // Unhandled 'error' event
^

TypeError: Cannot read property '10006' of undefined
at new WemoAccessory (/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:107:38)
at /usr/local/lib/node_modules/homebridge-platform-wemo/index.js:53:23
at /usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:147:7
at Parser. (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:483:18)
at emitOne (events.js:77:13)
at Parser.emit (events.js:169:7)
at Object.onclosetag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:444:26)
at emit (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:639:35)
at emitNode (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:644:5)
at closeTag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:903:7)
at Object.write (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1436:13)
at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:502:31)
at Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:7:59)
at Object.exports.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:534:19)
at parseResponse (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:137:12)
at /usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:97:5

**Comment by rudders** [comment]
Sorry for the late reply - been offline for a while. 

Can you tell me what devices you have? 

Looks like Washer is an insight which I can't directly test and it's binaryState of 8 is a new one on me.

If I give you some debug code could you run it for me so I can try and resolve remotely please - very odd that the registered Bulb has no 10006 property.

**Comment by rudders** [comment]
Downstream module was updated and I wasn't very specific on dependencies - please update to 0.5.6 which should pull wemo-client 0.6.1 now. Apologies!

**Comment by rudders** [comment]
Now at V0.5.9 so please update and re-test - hopefully this will resolve your issue.

**Comment by jhar3481** [comment]
That seems to have done the trick! Thanks so much!

**Comment by rudders** [comment]
Good to hear it worked.

**Comment by jhar3481** [comment]
Thanks again. Feel free to let me know if you still want that data.

**Comment by rudders** [comment]
Thanks but I sorted out this issue pretty definitely.... now on to some others....
