### ISSUE TITLE
iOS 11 Beta - single bulb out of 3 failure.

### ISSUE THREAD

**Issue by macbisho** [rudders/homebridge-platform-wemo#111]
Since installing dev. beta iOS 11 one of my Wemo light bulbs has gone rogue. 

Home.app says it's not supported - I've got 2 other Wemo light bulbs that are working perfectly well.

Not sure if this is an iOS 11 issue, a homebridge issue or a Wemo bulb issue (the bulb shows up in the Wemo app still, and I can adjust it fine, most of the time*, with that.

*it fails one in twenty times.

The bulb is still showing up in HomeBridge perfectly well... and if I pull out an iOS 10 device I can control it with Home.app - but it is very flaky.

**Comment by devbobo** [comment]
@macbisho I've had a similar issue with two different platform plugins on iOS11 (and seen similar reports from users of other plugins)...i'm not sure at this stage whether it's a HomeKit or Homebridge issue, but considering I have seen it on multiple plugins, I don't believe that it's a specific plugin issue.

**Comment by macbisho** [comment]
The latest homebridge update appears to have possibly fixed the issue... at least according to the notes:
Version bump to 0.4.25 (#1436)
New HAP-NodeJS version should resolve the issue with a device showing as "Not Supported" and issues from Apple removing Optional characteristics.

**Comment by oznu** [comment]
Similar issue. My Wemo Switch is working fine, but my Wemo Light Switch is not working and causes homebridge to crash.

```
homebridge        | [8/18/2017, 10:05:15 AM] [WeMo Platform] Online: Kitchen Light [undefined]
homebridge        | events.js:160
homebridge        |       throw er; // Unhandled 'error' event
homebridge        |       ^
homebridge        |
homebridge        | TypeError: Cannot read property 'length' of undefined
homebridge        |     at Characteristic.validateValue (/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/Characteristic.js:225:19)
homebridge        |     at Characteristic.setValue (/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/Characteristic.js:273:19)
homebridge        |     at Service.setCharacteristic (/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/Service.js:178:32)
homebridge        |     at new WemoAccessory (/homebridge/node_modules/homebridge-platform-wemo/index.js:335:10)
homebridge        |     at addDiscoveredDevice (/homebridge/node_modules/homebridge-platform-wemo/index.js:155:41)
homebridge        |     at /homebridge/node_modules/wemo-client/index.js:48:14
homebridge        |     at Parser.<anonymous> (/homebridge/node_modules/xml2js/lib/xml2js.js:489:18)
homebridge        |     at emitOne (events.js:96:13)
homebridge        |     at Parser.emit (events.js:188:7)
homebridge        |     at Object.onclosetag (/homebridge/node_modules/xml2js/lib/xml2js.js:447:26)
homebridge        |     at emit (/homebridge/node_modules/sax/lib/sax.js:640:35)
homebridge        |     at emitNode (/homebridge/node_modules/sax/lib/sax.js:645:5)
homebridge        |     at closeTag (/homebridge/node_modules/sax/lib/sax.js:905:7)
homebridge        |     at Object.write (/homebridge/node_modules/sax/lib/sax.js:1452:13)
homebridge        |     at Parser.exports.Parser.Parser.parseString (/homebridge/node_modules/xml2js/lib/xml2js.js:508:31)
homebridge        |     at Parser.parseString (/homebridge/node_modules/xml2js/lib/xml2js.js:7:59)
homebridge        |     at Object.exports.parseString (/homebridge/node_modules/xml2js/lib/xml2js.js:540:19)
homebridge        |     at IncomingMessage.<anonymous> (/homebridge/node_modules/wemo-client/client.js:67:16)
homebridge        |     at emitNone (events.js:91:20)
homebridge        |     at IncomingMessage.emit (events.js:185:7)
homebridge        |     at endReadableNT (_stream_readable.js:974:12)
homebridge        |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
```

Running Homebridge 0.4.25.
