### ISSUE TITLE
TypeError: Cannot read property 'addMembership' of null

### ISSUE THREAD

**Issue by Judas2016** [rudders/homebridge-platform-wemo#128]
This error "TypeError: Cannot read property 'addMembership' of null" just started w/my Wemo plugin on Homebridge.  This had been working fine for a long time without issue. I did an NPM upgrade on the plugin and still get the same error.  Anyone else having this happen?  It brings down the entire homebridge process...

/usr/local/lib/node_modules/homebridge-wemo/node_modules/node-ssdp/lib/index.js:189
Feb 12 14:31:58 raspberrypi bash[24759]: throw e
Feb 12 14:31:58 raspberrypi bash[24759]: ^
Feb 12 14:31:58 raspberrypi bash[24759]: TypeError: Cannot read property 'addMembership' of null
Feb 12 14:31:58 raspberrypi bash[24759]: at Timeout.addMembership [as _onTimeout] (/usr/local/lib/node_modules/homebridge-wemo/node_modules/node-ssdp/lib/index.js:182:18)
Feb 12 14:31:58 raspberrypi bash[24759]: at tryOnTimeout (timers.js:232:11)
Feb 12 14:31:58 raspberrypi bash[24759]: at Timer.listOnTimeout (timers.js:202:5)
Feb 12 14:31:58 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE

**Comment by Judas2016** [comment]
wrong plugin version
