### ISSUE TITLE
Wemo maker not working and crashing homebridge. ERROR

### ISSUE THREAD

**Issue by tomasakegreiss** [rudders/homebridge-platform-wemo#141]
I have hass.io setup in a raspberry pi and i am running homebridge add on. I have a wemo dimmer that works with homebridge but the second i plug in the wemo maker it crashes homebridge. 

this is the error that appears

events.js:183
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'forEach' of undefined
    at /usr/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:404:42
    at Parser.<anonymous> (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:5:59)
    at Object.exports.parseString (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:354:19)
    at Object.attributeList (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:400:14)
    at /usr/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:421:22
    at Parser.<anonymous> (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1436:13)

I want to setup the wemo maker as a garage door opener on the home app.

any help would be appreciate.

thanks

**Comment by DMBlakeley** [comment]
Did you stop Homebridge before plugging in the Wemo Maker and then restart Homebridge?

**Comment by tomasakegreiss** [comment]
yes. every time the wemo maker connect to the internet it crashes homebridge.

**Comment by tomasakegreiss** [comment]
is register by homebridge

[2018-5-16 19:24:11] [WeMo Platform] Online: Garage door [94103ED4059C]
[2018-5-16 19:24:11] [WeMo Platform] Garage door - Get Current Door State: Open

but then it crash.

[2018-5-16 19:25:16] [WeMo Platform] Garage door - Set Target Door State: Closed (triggered by External)
[2018-5-16 19:25:16] [WeMo Platform] Garage door - Get Current Door State: Closed
events.js:183
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'forEach' of undefined
    at /usr/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:404:42
    at Parser.<anonymous> (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:5:59)
    at Object.exports.parseString (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:354:19)
    at Object.attributeList (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:400:14)
    at /usr/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:421:22
    at Parser.<anonymous> (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1436:13)

**Comment by DMBlakeley** [comment]
I have the Wemo Maker installed on my garage door and have had not seen the issue you are reporting.  Do you have your Wemo Maker installed on the garage door with a sensor switch connected to indicate that the garage door is closed?  Without the sensor switch, Homebridge does not know the real state and may be why it crashes.

**Comment by tomasakegreiss** [comment]
I have a sensor switch connected to the Wemo maker  and on the homebridge add on it reads the sensor correctly.

**Comment by DMBlakeley** [comment]
I am running Homebridge on a Mac mini without issue.  If I understand correctly, you have hass.io and hombridge running on your raspberry pi.  Is there a possibility that the 2 applications are conflicting with each other?

**Comment by tomasakegreiss** [comment]
you are correct on the setup but hass.io is home assistant and it run inside home assitant. the wemo maker is conflicting in some way with homebridge on my setup.

**Comment by DMBlakeley** [comment]
A suggest ... try stoping Homebridge, delete the .homebridge/accessories/cachedAccessories file, make sure the Wemo devices are plugged in and connected to your intranet, and restart Homebridge.  When Homebridge restarts it will scan for Wemo devices and rebuild this file.  See if it still crashes.

**Comment by tomasakegreiss** [comment]
i just erase all my setup and re do it. 

its working now. thank you
