### ISSUE TITLE
Error while adding GarageDoorOpener via WemoMaker

### ISSUE THREAD

**Issue by smanders7** [rudders/homebridge-platform-wemo#165]
Experiencing this error while re-adding an instance of homebridge after removing "accessories" and "persist" folders.  I also bumped the MAC Address and Hub ID to make sure all the devices were added from scratch.  I did update to the latest version of Homebridge which is now coming back as 0.4.50.  I am running this on a raspberry-pi in a docker container.  I am seeing this error while discovering the WemoMaker as a GarageDoorOpener.

```
[11/11/2019, 6:23:05 AM] [WeMo Platform] Error: HTTP 400: <html><body><h1>400 Bad Request</h1></body></html>
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:69:12)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
Homebridge Application then restarts and the GarageDoor comes back as a "Switch" which is not how I have it setup.  Before attempting this, the WemoMaker had been working flawlessly for year+ with my GarageDoor.  I am running "Homebridge Platform Wemo" v1.3.8.  I'm interfacing this with iOS device running 13.2.2.  I'm running the most update to date firmware available for my WemoMaker, WeMo_WW_2.00.11423.PVT-OWRT-Maker.  The Wemo Maker still works as expected when interfacing directly from the iOS WemoApp.

Let me know if there is anymore information I can gather.

**Comment by smanders7** [comment]
Can't explain it, but I am not longer getting this error on subsequent reboots.  Closing.
