### ISSUE TITLE
TypeError: Cannot read property 'device' of undefined 

### ISSUE THREAD

**Issue by cnrd** [rudders/homebridge-platform-wemo#44]
Hi

When ever I try to use this plugin Homebridge crashes with the following error:

```
[6/2/2016, 3:12:01 AM] [WeMo Platform] Server Listening...
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'device' of undefined
    at /usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/index.js:34:29
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:445:26)
    at emit (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:905:7)
    at Object.write (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1449:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:503:31)
```

If I disable this plugin everything is running just fine.

My config.json:

```
{
    "bridge": {
        "name": "xxx homebridge",
        "username": "xx:xx:xx:xx:xx",
        "port": 51826,
        "pin": "xxx-xx-xxx"
    },

    "platforms": [{
        "platform": "PhilipsHue",
        "name": "Philips Hue",
        "ip_address": "xxx.xxx.xxx.xxx",
        "username": "xxx"
    }, {
        "platform": "cmdSwitch2",
        "switches": [{
            "name": "xxx",
            "on_cmd": "wakeonlan xx:xx:xx:xx:xx",
            "off_cmd": "xxx",
            "state_cmd": "ping -c 2 -W 1 xxx.xxx.xxx.xxx | grep -i '2 received'"
        }]}, {
          "platform": "BelkinWeMo",
          "name": "WeMo Platform",
          "expected_accessories" : "1",
          "timeout" : "25",
          "no_motion_timer": "60",
          "homekit_safe" : "1"
        }
    ],
    "accessories": [{
        "accessory": "SamsungTV",
        "name": "Samsung TV",
        "ip_address": "xxx.xxx.xxx.xxx",
        "send_delay": 400
    }]
}

**Comment by pattyland** [comment]
You put the WeMo platform outside the platform array. I has to be between the squared brackets
