### ISSUE TITLE
homebridge can't find light switch

### ISSUE THREAD

**Issue by heartlikedecember** [rudders/homebridge-platform-wemo#56]
Had homebridge with wemo platform running and working perfectly last night.  Today, my dad redid our wifi, moving to a new router and renaming the wireless network.  Setup my phone, wemo lightswitch and MacBook running the homebridge server to this new network and now the wemo platform can no longer find my light switch on the network.  WeMo app on iOS can discover the switch.  Tried wemo-discover and returned no results.  
****
[8/30/2016, 8:43:51 PM] Loaded plugin: homebridge-platform-wemo
[8/30/2016, 8:43:51 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[8/30/2016, 8:43:51 PM] ---
[8/30/2016, 8:43:52 PM] Loaded plugin: homebridge-wemo
[8/30/2016, 8:43:52 PM] Registering accessory 'homebridge-wemo.WeMo'
[8/30/2016, 8:43:52 PM] ---
[8/30/2016, 8:43:52 PM] Loaded config.json with 0 accessories and 1 platforms.
[8/30/2016, 8:43:52 PM] ---
[8/30/2016, 8:43:52 PM] Loading 1 platforms...
[8/30/2016, 8:43:52 PM] [WeMo Platform] Initializing BelkinWeMo platform...
[8/30/2016, 8:43:52 PM] [WeMo Platform] Wemo Platform Plugin Loaded 
[8/30/2016, 8:43:52 PM] [WeMo Platform] Fetching the Wemo Accessories, expecting 1 and will wait 60 seconds to find them.
[8/30/2016, 8:44:52 PM] [WeMo Platform] We have timed out and only discovered 0 of the specified 1 devices - try restarting homebridge or increasing timeout in config.json
[8/30/2016, 8:44:52 PM] [WeMo Platform] and you have indicated you'd like to keep your HomeKit config safe so we're crashing out
/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:110
                    throw new Error("homebridge-wemo-platform has intentially bought down HomeBridge - please restart - sorry but it's your HomeKit configuration we're protecting!");
                    ^

Error: homebridge-wemo-platform has intentially bought down HomeBridge - please restart - sorry but it's your HomeKit configuration we're protecting!
    at null._onTimeout (/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:110:27)
    at Timer.listOnTimeout (timers.js:92:15)
****

config.json file

****
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "platforms": [
	        {
	          "platform": "BelkinWeMo",
	          "name": "WeMo Platform",
	          "expected_accessories" : "1",
	          "timeout" : "60",
	          "no_motion_timer": "60",
	          "homekit_safe" : "1"
	        }   
	    ]
}
****

**Comment by devbobo** [comment]
please try the new `1.0.0` release
