### ISSUE TITLE
Crash when device type not supported. 

### ISSUE THREAD

**Issue by tekuonline** [rudders/homebridge-platform-wemo#61]
Thanks for your work @devbobo , I updated the repo and there seem to be an issue.

`events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'log' of undefined
    at getServiceType (/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:765:17)
    at WemoPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:128:23)
    at WemoPlatform.addDiscoveredDevice (/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:99:22)
    at /usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/index.js:48:14
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/node_modules/sax/lib/sax.js:645:5)`

It seems to be from the `this.log("Not Supported: %s", deviceType);` at line 765 in index.js
I switched it to `console.log` which seems to fix it. 
I have a Wemo CoffeeMaker that isn't supported yet

**Comment by devbobo** [comment]
thanks @tekuonline, fixed in `1.0.1`
