### ISSUE TITLE
please help with the following error

### ISSUE THREAD

**Issue by scottsuine** [rudders/homebridge-platform-wemo#67]
getting the following error when running homebridge

node -v 6.9.1
npm-v 3.10.9

[10/22/2016, 1:58:47 PM] Loaded plugin: homebridge-platform-wemo
[10/22/2016, 1:58:47 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[10/22/2016, 1:58:47 PM] ---
/usr/local/lib/node_modules/homebridge/lib/server.js:199
  var username = config.bridge.username;
                              ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:199:31)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:49:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

config.json

{
"platforms": [
       {
         "platform": "BelkinWeMo",
         "name": "WeMo Platform",
         "noMotionTimer": 60,
         "ignoredDevices": []
       }   
   ]
}

**Comment by devbobo** [comment]
This isn't a `homebridge-platform-wemo` issue, your `config.json` appears to be missing the `bridge` specific section.

https://github.com/nfarina/homebridge/blob/master/config-sample.json
