### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by thegoodness777** [rudders/homebridge-platform-wemo#74]
Any help is appreciated.

Getting this error when I run homebridge...

pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[11/26/2016, 6:45:44 AM] Loaded plugin: homebridge-platform-wemo
[11/26/2016, 6:45:44 AM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[11/26/2016, 6:45:44 AM] ---
[11/26/2016, 6:45:44 AM] Loaded config.json with 0 accessories and 1 platforms.
[11/26/2016, 6:45:44 AM] ---
[11/26/2016, 6:45:44 AM] Loading 1 platforms...
[11/26/2016, 6:45:44 AM] [WeMo Platform] Initializing BelkinWeMo platform...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[11/26/2016, 6:45:45 AM] Homebridge is running on port 51826.
[11/26/2016, 6:45:45 AM] [WeMo Platform] Online: Front Entrance [94103E4D77B8]
[11/26/2016, 6:45:45 AM] [WeMo Platform] Online: Living Room Ceiling Fan [94103E48B4BC]
[11/26/2016, 6:45:45 AM] [WeMo Platform] Online: Camera [B4750EE8DEFC]
[11/26/2016, 6:45:45 AM] [WeMo Platform] Online: Scentsy [94103E2E8DD4]
[11/26/2016, 6:45:45 AM] [WeMo Platform] Online: Front Porch [94103E452240]
[11/26/2016, 6:45:45 AM] [WeMo Platform] Online: Kitchen [94103E4D7B0C]
[11/26/2016, 6:45:46 AM] [WeMo Platform] Offline: Floor Lamp [94103EA2B2781382]
[11/26/2016, 6:45:46 AM] [WeMo Platform] Online: Bedroom-1 [94103EA2B277CD05]
[11/26/2016, 6:45:46 AM] [WeMo Platform] Bedroom-1 - Get brightness: 1%
[11/26/2016, 6:45:46 AM] [WeMo Platform] Online: Bedroom-2 [94103EA2B2782F12]
[11/26/2016, 6:45:46 AM] [WeMo Platform] Bedroom-2 - Get brightness: 1%
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'length' of undefined
    at WemoLinkAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:907:60)
    at /usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:207:7
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at SAXParser.onclosetag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/node_modules/sax/lib/sax.js:905:7)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/node_modules/xml2js/node_modules/sax/lib/sax.js:1449:13)

Here's my config.json:

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

    "platforms": [
        {
            "platform" : "BelkinWeMo",
            "name" : "WeMo Platform",
            "ignoredDevices" : "1"
        }
    ]
}

**Comment by devbobo** [comment]
@thegoodness777 this should be resolved in `version 1.1.6`

**Comment by thegoodness777** [comment]
@devbobo Thanks!

So I'm good to go, just waiting for an update? Any changes required on my part?

**Comment by devbobo** [comment]
the update is available, you shouldn't have to do anything.
