### ISSUE TITLE
Homebridge exiting with error when identifying WeMo devices

### ISSUE THREAD

**Issue by ikaika30** [rudders/homebridge-platform-wemo#83]
I have 5 devices with one set to ignored (and expected devices to "4"). They load in different orders.  The error does not seem to be related to any particular device and the error can occur after all four devices are recognized as online or only a few.

```
pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[1/30/2017, 9:13:54 AM] Loaded plugin: homebridge-platform-wemo
[1/30/2017, 9:13:54 AM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[1/30/2017, 9:13:54 AM] ---
[1/30/2017, 9:13:54 AM] config.json (/home/pi/.homebridge/config.json) not found.
Load homebridge-platform-wemo.BelkinWeMo
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[1/30/2017, 9:13:54 AM] Homebridge is running on port 35495.
[1/30/2017, 9:13:55 AM] [homebridge-platform-wemo.BelkinWeMo] Online: Garage Door [****]
[1/30/2017, 9:13:55 AM] [homebridge-platform-wemo.BelkinWeMo] Online: Bar Light [****]
[1/30/2017, 9:13:55 AM] [homebridge-platform-wemo.BelkinWeMo] Online: Front Lights [****]
[1/30/2017, 9:13:55 AM] [homebridge-platform-wemo.BelkinWeMo] Online: Side Yard [****]
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'forEach' of undefined
    at /usr/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:365:41
    at Parser.<anonymous> (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Object.onclosetag (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:905:7)
    at Object.write (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1449:13)
    at Parser.exports.Parser.Parser.parseString (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:508:31)
```

**Comment by ikaika30** [comment]
Okay, the issue was related to installing two new WeMo devices yesterday - the maker and one light switch .  The firmware update notice did not come through until after posting the issue. After upgrading the firmware homebridge seems to load just fine.
