### ISSUE TITLE
Error crashes Homebridge

### ISSUE THREAD

**Issue by UNiXMIT** [rudders/homebridge-platform-wemo#96]
I get the following error that crashes homebridge. Any ideas what's happening? Thanks.

events.js:163
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'UDN' of null
    at module.exports.addDiscoveredDevice (/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:102:43)
    at /usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/index.js:48:14
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:191:7)
    at SAXParser.onclosetag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:905:7)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1452:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:7:59)
    at Object.exports.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:540:19)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:67:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)

**Comment by kevinberthiaume** [comment]
Same issue for me.

events.js:160
throw er; // Unhandled 'error' event
TypeError: Cannot read property 'UDN' of null 
at addDiscoveredDevice (/usr/lib/node_modules/homebridge-platform-wemo/index.js:102:43)
at /usr/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/index.js:48:14
at Parser.<anonymous> (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:489:18)
at emitOne (events.js:96:13) 
at Parser.emit (events.js:188:7)
at Object.onclosetag (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:447:26)
at emit (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:640:35) 
at emitNode (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:645:5) 
at closeTag (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:905:7) 
at Object.write (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1452:13) 
at Parser.exports.Parser.Parser.parseString (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:508:31) 
at Parser.parseString (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:7:59) 
at Object.exports.parseString (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:540:19) 
at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:67:16) 
at emitNone (events.js:91:20) 
at IncomingMessage.emit (events.js:185:7)

**Comment by UNiXMIT** [comment]
Because I only use a WeMo switch the workaround for me at the moment is to use homebridge-wemo instead. This works fine for me with no issues.

**Comment by denislooby** [comment]
Looking at wemo-client it appears the callback has changed from 
`cb.call(self, device);`
to
`cb.call(self, err, device);`
in version 0.13

I'm running homebridge in a docker container and had left install.sh lying around, so it updates the modules every time it starts, which is why it started happening suddenly when it pulled down the updated wemo-client.

I've opened a pull request that changes the call back in the platform to match the new one in the wemo-client library.
As my node skills are limited I've only added the err parameter and done nothing with it.

If you make the same change to your local copy of the homebridge-platform-wemo library it should get it working again.
If you're not sure how to do that then you're probably best to wait for an updated release of this platform.

**Comment by dragilias** [comment]
Worked like a charm, thanks for the help!

**Comment by devbobo** [comment]
should be fixed now 👍

**Comment by rdmarsh** [comment]
Thanks. Also confirming working for me with 1.3.0
